import { MythrasWeapon } from './mythras-api';
export const DEFAULT_ARMORY: MythrasWeapon[] = 
[
  {
    "name": "Club",
    "type": "1h-melee",
    "damage": "1d6",
    "size": "M",
    "ap": "4",
    "hp": "4",
    "specialFx": "Bash, Stun Location",
    "traits": "",
    "cost": "5SP"
  },
  {
    "name": "Dagger",
    "type": "1h-melee",
    "damage": "1d4+1",
    "size": "S",
    "ap": "6",
    "hp": "8",
    "specialFx": "Bleed, Impale",
    "traits": "Thrown",
    "cost": "3GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC"
  },
  {
    "name": "Great club",
    "type": "2h-melee",
    "damage": "2d6",
    "size": "H",
    "ap": "4",
    "hp": "10",
    "specialFx": "Bash, Stun Location",
    "traits": "",
    "cost": "5GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Hand axe",
    "type": "1h-melee",
    "damage": "1d6",
    "size": "S",
    "ap": "3",
    "hp": "6",
    "specialFx": "Bleed",
    "traits": "Thrown",
    "cost": "2.5GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC"
  },
  {
    "name": "Longspear",
    "type": "2h-melee",
    "damage": "1d10+1",
    "size": "L",
    "ap": "4",
    "hp": "10",
    "specialFx": "Impale",
    "traits": "Set",
    "cost": "3GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Mace",
    "type": "1h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "6",
    "hp": "6",
    "specialFx": "Bash, Stun Location",
    "traits": "",
    "cost": "10GP"
  },
  {
    "name": "Mace, heavy",
    "type": "2h-melee",
    "damage": "1d8+2",
    "size": "M",
    "ap": "6",
    "hp": "10",
    "specialFx": "Bash, Stun Location",
    "traits": "",
    "cost": "20GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Morning star",
    "type": "1h-melee",
    "damage": "2d4",
    "size": "M",
    "ap": "4",
    "hp": "10",
    "specialFx": "Bash, Stun Location",
    "traits": "",
    "cost": "15GP"
  },
  {
    "name": "Quarterstaff",
    "type": "2h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "4",
    "hp": "8",
    "specialFx": "Stun Location",
    "traits": "",
    "cost": "2GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Shortspear",
    "type": "1h-melee",
    "damage": "1d8+1",
    "size": "M",
    "ap": "4",
    "hp": "5",
    "specialFx": "Impale",
    "traits": "Throw, Set",
    "cost": "2GP"
  },
  {
    "name": "Sickle",
    "type": "1h-melee",
    "damage": "1d6",
    "size": "M",
    "ap": "3",
    "hp": "8",
    "specialFx": "Bleed, Impale",
    "traits": "",
    "cost": "7GP"
  },
  {
    "name": "Ball & chain",
    "type": "1h-melee",
    "damage": "1d6+1",
    "size": "M",
    "ap": "6",
    "hp": "8",
    "specialFx": "Bash, Entangle, Stun Location",
    "traits": "Flexible",
    "cost": "25GP"
  },
  {
    "name": "Bastard sword (1H)",
    "type": "1h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "6",
    "hp": "12",
    "specialFx": "Bleed, Impale, +Sunder (2H)",
    "traits": "",
    "cost": "25GP"
  },
  {
    "name": "Bastard sword (2H)",
    "type": "2h-melee",
    "damage": "1d10",
    "size": "L",
    "ap": "6",
    "hp": "12",
    "specialFx": "Bleed, Impale, +Sunder (2H)",
    "traits": "",
    "cost": "25GP"
  },
  {
    "name": "Battleaxe (1H)",
    "type": "1h-melee",
    "damage": "1d6+1",
    "size": "M",
    "ap": "4",
    "hp": "8",
    "specialFx": "Bleed, Sunder",
    "traits": "",
    "cost": "10GP"
  },
  {
    "name": "Battleaxe (2H)",
    "type": "2h-melee",
    "damage": "1d8+1",
    "size": "L",
    "ap": "4",
    "hp": "8",
    "specialFx": "Bleed, Sunder",
    "traits": "",
    "cost": "10GP"
  },
  {
    "name": "Broadsword",
    "type": "1h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "6",
    "hp": "10",
    "specialFx": "Bleed, Impale",
    "traits": "",
    "cost": "18GP"
  },
  {
    "name": "Chain",
    "type": "1h-melee",
    "damage": "1d4",
    "size": "M",
    "ap": "8",
    "hp": "6",
    "specialFx": "Bash, Entangle",
    "traits": "",
    "cost": "1GP"
  },
  {
    "name": "Falchion",
    "type": "1h-melee",
    "damage": "1d6+2",
    "size": "M",
    "ap": "6",
    "hp": "10",
    "specialFx": "Bleed",
    "traits": "",
    "cost": "20GP"
  },
  {
    "name": "Flail",
    "type": "1h-melee",
    "damage": "1d6",
    "size": "M",
    "ap": "3",
    "hp": "6",
    "specialFx": "Bash",
    "traits": "Flexible",
    "cost": "2.5GP"
  },
  {
    "name": "Flail, heavy",
    "type": "2h-melee",
    "damage": "1d10",
    "size": "L",
    "ap": "4",
    "hp": "10",
    "specialFx": "Bash, Stun Location",
    "traits": "Flexible",
    "cost": "25GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Garrote",
    "type": "2h-melee",
    "damage": "1d2",
    "size": "S",
    "ap": "1",
    "hp": "2",
    "specialFx": "\u2014",
    "traits": "Stealth",
    "cost": "1.5GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC"
  },
  {
    "name": "Glaive",
    "type": "2h-melee",
    "damage": "1d10+2",
    "size": "L",
    "ap": "4",
    "hp": "10",
    "specialFx": "Bleed, Sunder",
    "traits": "",
    "cost": "25GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Great axe",
    "type": "2h-melee",
    "damage": "2d6+2",
    "size": "H",
    "ap": "4",
    "hp": "10",
    "specialFx": "Bleed, Sunder",
    "traits": "",
    "cost": "15GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Great hammer",
    "type": "2h-melee",
    "damage": "1d10+3",
    "size": "H",
    "ap": "4",
    "hp": "10",
    "specialFx": "Bash, Stun Location, Sunder",
    "traits": "",
    "cost": "25GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Great sword",
    "type": "2h-melee",
    "damage": "2d8",
    "size": "H",
    "ap": "6",
    "hp": "12",
    "specialFx": "Bleed, Impale, Sunder",
    "traits": "",
    "cost": "30GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Halberd/ Poleaxe",
    "type": "2h-melee",
    "damage": "1d8+2",
    "size": "L",
    "ap": "4",
    "hp": "10",
    "specialFx": "Entangle, Impale, Sunder",
    "traits": "Set",
    "cost": "20GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Knife",
    "type": "1h-melee",
    "damage": "1d3",
    "size": "S",
    "ap": "5",
    "hp": "4",
    "specialFx": "Bleed, Impale",
    "traits": "",
    "cost": "1GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC"
  },
  {
    "name": "Lance",
    "type": "1h-melee",
    "damage": "1d10+2",
    "size": "H",
    "ap": "4",
    "hp": "10",
    "specialFx": "Impale, Sunder",
    "traits": "Mount",
    "cost": "15GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Longsword",
    "type": "1h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "6",
    "hp": "12",
    "specialFx": "Bleed, Impale",
    "traits": "",
    "cost": "20GP"
  },
  {
    "name": "Main gauche",
    "type": "1h-melee",
    "damage": "1d4",
    "size": "S",
    "ap": "6",
    "hp": "10",
    "specialFx": "Bleed, Impale",
    "traits": "Entrapping",
    "cost": "18GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC"
  },
  {
    "name": "Military pick",
    "type": "1h-melee",
    "damage": "1d6+1",
    "size": "M",
    "ap": "6",
    "hp": "10",
    "specialFx": "Stun Location, Sunder",
    "traits": "",
    "cost": "18GP"
  },
  {
    "name": "Military pick, heavy",
    "type": "2h-melee",
    "damage": "1d8+2",
    "size": "L",
    "ap": "6",
    "hp": "10",
    "specialFx": "Impale, Stun Location, Sunder",
    "traits": "",
    "cost": "25GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Net",
    "type": "1h-melee",
    "damage": "1d4",
    "size": "S",
    "ap": "2",
    "hp": "20",
    "specialFx": "Entangle",
    "traits": "Entrapping",
    "cost": "2GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC"
  },
  {
    "name": "Pike",
    "type": "2h-melee",
    "damage": "1d10+2",
    "size": "L",
    "ap": "4",
    "hp": "12",
    "specialFx": "Impale",
    "traits": "Set",
    "cost": "9GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Rapier",
    "type": "1h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "5",
    "hp": "8",
    "specialFx": "Impale",
    "traits": "",
    "cost": "10GP"
  },
  {
    "name": "Saber",
    "type": "1h-melee",
    "damage": "1d6+1",
    "size": "M",
    "ap": "6",
    "hp": "8",
    "specialFx": "Bleed, Impale",
    "traits": "",
    "cost": "23GP"
  },
  {
    "name": "Scimitar",
    "type": "1h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "6",
    "hp": "10",
    "specialFx": "Bleed",
    "traits": "",
    "cost": "20GP"
  },
  {
    "name": "Shortsword",
    "type": "1h-melee",
    "damage": "1d6",
    "size": "M",
    "ap": "6",
    "hp": "8",
    "specialFx": "Bleed, Impale",
    "traits": "",
    "cost": "10GP"
  },
  {
    "name": "Trident",
    "type": "1h-melee",
    "damage": "1d8",
    "size": "M",
    "ap": "4",
    "hp": "10",
    "specialFx": "Impale",
    "traits": "Barbed",
    "cost": "16GP"
  },
  {
    "name": "War hammer",
    "type": "1h-melee",
    "damage": "1d8+1",
    "size": "M",
    "ap": "3",
    "hp": "8",
    "specialFx": "Stun Location",
    "traits": "",
    "cost": "15GP"
  },
  {
    "name": "Whip",
    "type": "1h-melee",
    "damage": "1d3",
    "size": "M",
    "ap": "2",
    "hp": "8",
    "specialFx": "Stun Location",
    "traits": "Flexible, Entrapping",
    "cost": "10GP",
    "notes": "Does not add damage modifier"
  },
  {
    "name": "Buckler",
    "type": "shield",
    "damage": "1d3",
    "size": "M",
    "ap": "6",
    "hp": "9",
    "specialFx": "Bash, Stun Location",
    "traits": "Ranged Parry; Passive Block 2 locations",
    "cost": "5GP"
  },
  {
    "name": "Heater",
    "type": "shield",
    "damage": "1d4",
    "size": "L",
    "ap": "6",
    "hp": "12",
    "specialFx": "Bash, Stun Location",
    "traits": "Ranged Parry; Passive Block 3 locations",
    "cost": "15GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Kite",
    "type": "shield",
    "damage": "1d4",
    "size": "H",
    "ap": "4",
    "hp": "15",
    "specialFx": "Bash, Stun Location",
    "traits": "Ranged Parry; Passive Block 4 locations",
    "cost": "30GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Round",
    "type": "shield",
    "damage": "1d4",
    "size": "L",
    "ap": "4",
    "hp": "12",
    "specialFx": "Bash, Stun Location",
    "traits": "Ranged Parry; Passive Block 4 locations",
    "cost": "30GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Target",
    "type": "shield",
    "damage": "1d3+1",
    "size": "L",
    "ap": "4",
    "hp": "9",
    "specialFx": "Bash, Impale",
    "traits": "Ranged Parry; Passive Block 3 locations",
    "cost": "15GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Tower",
    "type": "shield",
    "damage": "1d4",
    "size": "H",
    "ap": "4",
    "hp": "18",
    "specialFx": "Bash, Stun Location",
    "traits": "Ranged Parry; Passive Block 5 locations",
    "cost": "30GP",
    "notes": "Counts as 2 Things with regards to ENC"
  },
  {
    "name": "Crossbow, heavy",
    "type": "ranged",
    "damage": "1d10",
    "size": "H",
    "ap": "4",
    "hp": "8",
    "specialFx": "Impale, Sunder",
    "traits": "",
    "cost": "35GP",
    "notes": "Counts as 2 Things with regards to ENC",
    "range": "60/450/900",
    "load": "4",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Crossbow, light",
    "type": "ranged",
    "damage": "1d8",
    "size": "L",
    "ap": "4",
    "hp": "5",
    "specialFx": "Impale",
    "traits": "",
    "cost": "15GP",
    "range": "60/300/600",
    "load": "3",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Dagger",
    "type": "ranged",
    "damage": "1d4",
    "size": "S",
    "ap": "4",
    "hp": "6",
    "specialFx": "Impale",
    "traits": "",
    "cost": "3GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC, has the 1H trait",
    "range": "15/30/60",
    "load": "\u2014",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Dart",
    "type": "ranged",
    "damage": "1d4",
    "size": "S",
    "ap": "2",
    "hp": "1",
    "specialFx": "Impale",
    "traits": "",
    "cost": "1GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC, has the 1H trait",
    "range": "15/30/60",
    "load": "\u2014",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Short Spear",
    "type": "ranged",
    "damage": "1d8",
    "size": "L",
    "ap": "4",
    "hp": "5",
    "specialFx": "Impale",
    "traits": "",
    "cost": "2GP",
    "range": "30/45/90",
    "load": "\u2014",
    "impSize": "M",
    "damageModifier": false
  },
  {
    "name": "Sling",
    "type": "ranged",
    "damage": "1d8",
    "size": "L",
    "ap": "1",
    "hp": "2",
    "specialFx": "Stun Location",
    "traits": "",
    "cost": "5SP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC, has the 1H trait",
    "range": "30/450/900",
    "load": "3",
    "impSize": "\u2014",
    "damageModifier": false
  },
  {
    "name": "Stone or Rock",
    "type": "ranged",
    "damage": "1d3",
    "size": "S",
    "ap": "0",
    "hp": "0",
    "specialFx": "Stun Location",
    "traits": "",
    "cost": "\u2014",
    "range": "15/75/150",
    "load": "\u2014",
    "impSize": "\u2014",
    "damageModifier": false
  },
  {
    "name": "Bow, long",
    "type": "ranged",
    "damage": "1d8",
    "size": "H",
    "ap": "4",
    "hp": "7",
    "specialFx": "Impale",
    "traits": "",
    "cost": "20GP",
    "range": "45/375/750",
    "load": "2",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Bow, short",
    "type": "ranged",
    "damage": "1d6",
    "size": "L",
    "ap": "4",
    "hp": "4",
    "specialFx": "Impale",
    "traits": "",
    "cost": "7.5GP",
    "range": "45/300/600",
    "load": "2",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Bow, composite long",
    "type": "ranged",
    "damage": "1d8",
    "size": "H",
    "ap": "4",
    "hp": "8",
    "specialFx": "Impale",
    "traits": "",
    "cost": "25GP",
    "range": "50/400/800",
    "load": "2",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Bow, composite short",
    "type": "ranged",
    "damage": "1d6",
    "size": "L",
    "ap": "4",
    "hp": "5",
    "specialFx": "Impale",
    "traits": "",
    "cost": "9GP",
    "range": "50/325/650",
    "load": "2",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Crossbow, light repeating",
    "type": "ranged",
    "damage": "1d8",
    "size": "L",
    "ap": "4",
    "hp": "5",
    "specialFx": "Impale",
    "traits": "",
    "cost": "75GP",
    "notes": "Counts as 2 Things with regards to ENC, has the Dwarf and Repeating traits",
    "range": "60/300/600",
    "load": "\u2014",
    "impSize": "S",
    "damageModifier": false
  },
  {
    "name": "Hand axe",
    "type": "ranged",
    "damage": "1d6",
    "size": "S",
    "ap": "4",
    "hp": "6",
    "specialFx": "Bleed",
    "traits": "",
    "cost": "2.5GP",
    "notes": "Counts as \u00bd of a Thing with regards to ENC, has the 1H trait",
    "range": "30/60/90",
    "load": "\u2014",
    "impSize": "\u2014",
    "damageModifier": false
  }
];
